export const exportCopy = {
  zh: {
    title: "匯出個人資料", back: "返回", password: "請輸入目前密碼",
    description: "匯出本人帳號、通知，以及本人建立且目前仍有權存取的照護紀錄。包含藥單明細、健康紀錄、服藥紀錄、記事、行事曆及本人聊天室訊息；不包含其他成員帳號、完整長者檔案、圖片／音檔本體或媒體下載連結。",
    warning: "JSON 可能含敏感健康資料，且未加密。請只存放或分享至可信任的位置。匯出檔不會上傳至公開網址；下載或分享出去的副本需由你自行管理。",
    generate: "重新驗證並產生 JSON", busy: "處理中…",
    download: "下載 JSON", share: "儲存／分享 JSON",
    ready: "已產生匯出檔", count: "紀錄筆數", skipped: "略過無存取權或歸屬不符的紀錄",
    done: "已交由瀏覽器下載／系統分享處理；是否完成儲存請在所選位置確認。",
    failed: "匯出失敗，未提供不完整檔案。請稍後重試。",
    authFailed: "重新驗證失敗，請確認目前密碼。",
    limited: "已達匯出次數或資料量上限（每小時 3 次、最多 5,000 筆掃描／4 MiB）。請稍後重試；若資料過多，請聯絡團隊協助匯出。",
    unavailable: "此裝置不支援檔案分享，請改用網頁版下載。",
    expired: "匯出資料已清除或超過 5 分鐘，請重新驗證產生。",
  },
  en: {
    title: "Export personal data", back: "Back", password: "Current password",
    description: "Export your account, notifications and records you authored that you can still access: prescriptions and items, health and medication records, notes, calendar events and your chat messages. Other user profiles, full patient profiles, media files and media URLs are excluded.",
    warning: "The unencrypted JSON may contain sensitive health data. Save or share only to a trusted location. No public download URL is created. You manage any saved or shared copies.",
    generate: "Verify and generate JSON", busy: "Working…", download: "Download JSON",
    share: "Save / share JSON", ready: "Export prepared", count: "Records",
    skipped: "Inaccessible or ownership-mismatched records omitted",
    done: "Handed to your browser or share sheet. Check the destination to confirm saving.",
    failed: "Export failed. No incomplete file was provided. Try again.",
    authFailed: "Verification failed. Check your current password.",
    limited: "Export limit reached: 3 per hour, 5,000 scanned documents / 4 MiB. Retry later or contact the team for larger exports.",
    unavailable: "File sharing is unavailable. Use the web app to download.",
    expired: "Export cleared or older than 5 minutes. Verify and generate again.",
  },
  vi: {
    title: "Xuất dữ liệu cá nhân", back: "Quay lại", password: "Mật khẩu hiện tại",
    description: "Xuất tài khoản, thông báo và bản ghi do bạn tạo mà bạn vẫn có quyền truy cập: đơn thuốc, sức khỏe, dùng thuốc, ghi chú, lịch và tin nhắn của bạn. Không gồm hồ sơ người khác, hồ sơ đầy đủ của người được chăm sóc, tệp hoặc liên kết đa phương tiện.",
    warning: "JSON không được mã hóa và có thể chứa dữ liệu sức khỏe nhạy cảm. Chỉ lưu hoặc chia sẻ đến nơi tin cậy. Không tạo liên kết tải công khai; bạn quản lý các bản sao đã lưu.",
    generate: "Xác minh và tạo JSON", busy: "Đang xử lý…", download: "Tải JSON",
    share: "Lưu / chia sẻ JSON", ready: "Đã tạo tệp", count: "Số bản ghi",
    skipped: "Bỏ qua bản ghi không có quyền hoặc không thuộc về bạn",
    done: "Đã chuyển đến trình duyệt hoặc bảng chia sẻ. Hãy kiểm tra nơi lưu.",
    failed: "Xuất thất bại. Không cung cấp tệp chưa đầy đủ. Hãy thử lại.",
    authFailed: "Xác minh thất bại. Kiểm tra mật khẩu hiện tại.",
    limited: "Giới hạn: 3 lần/giờ, 5.000 tài liệu / 4 MiB. Thử lại sau hoặc liên hệ nhóm nếu dữ liệu quá lớn.",
    unavailable: "Không hỗ trợ chia sẻ tệp. Hãy tải bằng ứng dụng web.",
    expired: "Dữ liệu đã xóa hoặc quá 5 phút. Hãy xác minh và tạo lại.",
  },
  id: {
    title: "Ekspor data pribadi", back: "Kembali", password: "Kata sandi saat ini",
    description: "Ekspor akun, notifikasi, dan catatan buatan Anda yang masih dapat diakses: resep, kesehatan, obat, catatan, kalender, dan pesan Anda. Profil pengguna lain, profil lengkap pasien, berkas media, dan tautan media tidak disertakan.",
    warning: "JSON tidak terenkripsi dan dapat berisi data kesehatan sensitif. Simpan atau bagikan hanya ke lokasi tepercaya. Tidak ada tautan unduhan publik; Anda mengelola salinan yang disimpan.",
    generate: "Verifikasi dan buat JSON", busy: "Memproses…", download: "Unduh JSON",
    share: "Simpan / bagikan JSON", ready: "Ekspor siap", count: "Catatan",
    skipped: "Catatan tanpa akses atau bukan milik Anda dilewati",
    done: "Diserahkan ke browser atau menu berbagi. Periksa lokasi penyimpanan.",
    failed: "Ekspor gagal. Tidak ada berkas tidak lengkap yang diberikan. Coba lagi.",
    authFailed: "Verifikasi gagal. Periksa kata sandi saat ini.",
    limited: "Batas: 3 per jam, 5.000 dokumen / 4 MiB. Coba lagi nanti atau hubungi tim untuk data lebih besar.",
    unavailable: "Berbagi berkas tidak tersedia. Gunakan aplikasi web untuk mengunduh.",
    expired: "Ekspor dihapus atau lebih dari 5 menit. Verifikasi dan buat ulang.",
  },
};
