const zh = {
  title: "角色與邀請管理", primaryOnly: "僅主要家屬可管理邀請或修改藥單。其他成員仍可查看資料及記錄服藥、健康狀況。",
  loading: "正在確認權限…", back: "返回", refresh: "重新整理", regenerate: "重新產碼", revoke: "撤銷邀請", approve: "核准", reject: "拒絕",
  warning: "重新產碼或撤銷會使舊碼及其待核准申請失效，不會移除已加入成員。", confirm: "確認執行？", cancel: "取消", error: "操作失敗，請重新整理後再試。",
  validity: "邀請碼限 24 小時內使用一次。送出申請即消耗邀請碼，主要家屬核准前無法讀取長者資料。", expires: "到期時間", applicant: "申請人 UID（請先核對身分）", role: "角色", primary: "主要家屬", secondary: "次要家屬", caregiver: "照護員", noPatient: "請先選擇長者。",
  requests: "我的加入申請（最近 50 筆）", empty: "目前沒有申請", enter: "進入已核准的長者", submitted: "申請已送出，請等待主要家屬核准。", active: "可使用", pending: "待核准", approved: "已核准", rejected: "已拒絕", revoked: "已撤銷", expired: "已過期",
};
type Copy = Record<keyof typeof zh, string>;
export const invitationCopy: Record<"zh" | "en" | "vi" | "id", Copy> = {
  zh,
  en: {title: "Roles and invitations", primaryOnly: "Only the primary family member can manage invitations or edit prescriptions. Others can view records and record medication and health readings.", loading: "Checking access…", back: "Back", refresh: "Refresh", regenerate: "New code", revoke: "Revoke", approve: "Approve", reject: "Reject", warning: "Replacing or revoking a code cancels its pending application, without removing approved members.", confirm: "Confirm action?", cancel: "Cancel", error: "Action failed. Refresh and try again.", validity: "One use within 24 hours. Submitting consumes the code. Patient access requires primary-family approval.", expires: "Expires", applicant: "Applicant UID (verify identity first)", role: "Role", primary: "Primary family", secondary: "Secondary family", caregiver: "Caregiver", noPatient: "Select a patient first.", requests: "My applications (latest 50)", empty: "No applications", enter: "Open approved patient", submitted: "Submitted. Await primary-family approval.", active: "Active", pending: "Pending", approved: "Approved", rejected: "Rejected", revoked: "Revoked", expired: "Expired"},
  vi: {title: "Vai trò và lời mời", primaryOnly: "Chỉ người nhà chính được quản lý lời mời và sửa đơn thuốc. Người khác được xem và ghi nhận dùng thuốc, sức khỏe.", loading: "Đang kiểm tra…", back: "Quay lại", refresh: "Làm mới", regenerate: "Tạo mã mới", revoke: "Thu hồi", approve: "Duyệt", reject: "Từ chối", warning: "Tạo mã mới hoặc thu hồi sẽ hủy đơn chờ duyệt, không xóa thành viên đã được duyệt.", confirm: "Xác nhận?", cancel: "Hủy", error: "Thao tác thất bại. Làm mới và thử lại.", validity: "Mã dùng một lần trong 24 giờ. Gửi đơn sẽ dùng hết mã. Cần người nhà chính duyệt để truy cập.", expires: "Hết hạn", applicant: "UID người đăng ký (xác minh trước)", role: "Vai trò", primary: "Người nhà chính", secondary: "Người nhà phụ", caregiver: "Người chăm sóc", noPatient: "Hãy chọn người được chăm sóc.", requests: "Đơn của tôi (50 đơn gần nhất)", empty: "Chưa có đơn", enter: "Mở hồ sơ đã duyệt", submitted: "Đã gửi. Chờ người nhà chính duyệt.", active: "Còn hiệu lực", pending: "Chờ duyệt", approved: "Đã duyệt", rejected: "Bị từ chối", revoked: "Đã thu hồi", expired: "Hết hạn"},
  id: {title: "Peran dan undangan", primaryOnly: "Hanya keluarga utama dapat mengelola undangan dan mengubah resep. Anggota lain dapat melihat serta mencatat obat dan kesehatan.", loading: "Memeriksa akses…", back: "Kembali", refresh: "Muat ulang", regenerate: "Kode baru", revoke: "Cabut", approve: "Setujui", reject: "Tolak", warning: "Kode baru atau pencabutan membatalkan permohonan tertunda, tanpa menghapus anggota yang disetujui.", confirm: "Konfirmasi?", cancel: "Batal", error: "Gagal. Muat ulang dan coba lagi.", validity: "Sekali pakai dalam 24 jam. Pengajuan menghabiskan kode. Akses memerlukan persetujuan keluarga utama.", expires: "Kedaluwarsa", applicant: "UID pemohon (verifikasi dahulu)", role: "Peran", primary: "Keluarga utama", secondary: "Keluarga sekunder", caregiver: "Perawat", noPatient: "Pilih pasien dahulu.", requests: "Permohonan saya (50 terbaru)", empty: "Tidak ada permohonan", enter: "Buka pasien yang disetujui", submitted: "Terkirim. Tunggu persetujuan keluarga utama.", active: "Aktif", pending: "Menunggu", approved: "Disetujui", rejected: "Ditolak", revoked: "Dicabut", expired: "Kedaluwarsa"},
};
